apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: twoge-cluster-mw
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: false
    privateNetworking: false
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
