apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: twoge-mikhail-cluster2
  region: us-east-1
  version: '1.32'

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: false
    privateNetworking: false
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"