apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: twoge-cluster
  region: us-east-1
  version: "1.27"

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: twoge-key 