apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: twoge-cluster-mw
  region: us-east-1
nodeGroups:
  - name: minimal-ng
    instanceType: m5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 20
    ssh:
      allow: false
