apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  
  namespace: twoge-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3