apiVersion: v1
kind: Service
metadata:
  name: twoge-service
  namespace: twoge-app
spec:
  type: LoadBalancer  # Change from NodePort to LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: twoge