apiVersion: v1
kind: Service
metadata:
  name: twoge-service
  namespace: twoge-namespace
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: twoge