apiVersion: v1
kind: Service
metadata:
  name: twoge-service
  namespace: twoge-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  selector:
    app: twoge