apiVersion: apps/v1
kind: Deployment
metadata:
  name: twoge-deployment
  namespace: twoge-app
  labels:
    app: twoge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: twoge
  template:
    metadata:
      labels:
        app: twoge
    spec:
      containers:
      - name: twoge
        image: mikhailg215/twoge:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: FLASK_RUN_PORT
          value: "5000"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: twoge-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: twoge-config
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: twoge-config
              key: DB_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: twoge-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: twoge-secrets
              key: DB_PASSWORD